In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel(r'C:\Users\Siddharth\Desktop\certificates\internshiptask\mini-project\Data-Science-Intern-2-Mini-Project-Task-master\Task 1 Data set\default_of_credit_card_clients.xls')

In [4]:
import numpy as np

In [5]:
np.random.seed(seed=24)


In [38]:
random_integers = np.random.randint(low=1,high=10,size=20)
random_integers

array([7, 3, 7, 5, 5, 3, 8, 4, 6, 5, 8, 8, 9, 7, 7, 3, 5, 8, 7, 1])

In [39]:
is_equal_to_3 = random_integers == 3
is_equal_to_3[:5]

array([False,  True, False, False, False])

In [8]:
is_equal_to_3[:5]


array([ True, False, False, False, False])

In [20]:
sum(is_equal_to_3)


36

In [41]:
random_integers[is_equal_to_3]


array([3, 3, 3])

In [22]:
id_counts = df['ID'].value_counts()
dupe_mask = id_counts == 2
dupe_mask[0:5]

NameError: name 'df' is not defined

In [ ]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids = list(dupe_ids)
len(dupe_ids)

In [ ]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 


In [ ]:
df_zero_mask = df == 0


In [ ]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)


In [ ]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [ ]:
df_clean_1['ID'].nunique()


In [ ]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

In [ ]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()


In [ ]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2[['PAY_1', 'PAY_2']].info()

In [ ]:
df_clean_2['EDUCATION'].replace(to_replace=[0, 5, 6], value=4, inplace=True)
df_clean_2['EDUCATION'].value_counts()

In [ ]:
df_clean_2['MARRIAGE'].replace(to_replace=0, value=3, inplace=True)
df_clean_2['MARRIAGE'].value_counts()

In [ ]:
df_clean_2['EDUCATION_CAT'] = 'none'


In [ ]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)


In [ ]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [ ]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

In [ ]:
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)
df_with_ohe.to_csv('cleaned_data.csv', index=False)
